### PR TITLE
tree-wide: replace tabs with spaces

### PR DESCRIPTION
**Pull request by mrc0mmand**
And two other fixes for issues reported by LGTM.

### CODE REVIEW

**Comment by evverx** [comment]
@mrc0mmand I wonder if it would make sense to follow the systemd style guide and use 8 spaces? 4 spaces are fine too but it isn't consistent across the systemd organization.

**Comment by mrc0mmand** [comment]
> @mrc0mmand I wonder if it would make sense to follow the systemd style guide and use 8 spaces? 4 spaces are fine too but it isn't consistent across the systemd organization.

That would definitely make sense, I'll tweak the commit.

**Comment by evverx** [comment]
LGTM. Thanks!

**Comment by evverx** [comment]
@mrc0mmand speaking of the systemd style guide now that `systemd-dfuzzer` is out of sync with `dfuzzer` would it be OK if I renamed `master` to `main`?

**Comment by mrc0mmand** [comment]
> @mrc0mmand speaking of the systemd style guide now that `systemd-dfuzzer` is out of sync with `dfuzzer` would it be OK if I renamed `master` to `main`?

~~Not at all~~ Definitely, go ahead :-)

**Pull request merged**
