### PR TITLE
Argument parsing tweaks

### PR DESCRIPTION
**Pull request by mrc0mmand**

### CODE REVIEW

**Comment by mrc0mmand** [comment]
The tabs everywhere are driving me nuts (see the formatting of the longopts struct), but it is what it is :-)

@evverx PTAL, after some cleanups I'd like to get to the _useful_ stuff (especially "advanced signatures"), which could yield interesting results.

**Comment by evverx** [comment]
@mrc0mmand thanks! I'll take a closer look a bit later today but in the meantime could you run something like
```sh
dfuzzer --help
dfuzzer --verbose --bus ...
```
on GHAction in addition to the commands with short options just to make sure the long options are more or less in good shape as well?

> The tabs everywhere are driving me nuts (see the formatting of the longopts struct), but it is what it is :-)

Considering that `dfuzzer` is no longer actively maintained and the patches are unlikely to land there I think it should be possible to just reformat the code in a separate PR.

**Comment by evverx** [comment]
FWIW I tried to turn on LGTM here but judging by https://lgtm.com/projects/g/systemd/systemd-dfuzzer it can't be built automatically without `.lgtm.yml` where `make -C src` would be run explicitly :-(

**Comment by evverx** [comment]
LGTM should be able to build dfuzzer once https://github.com/systemd/systemd-dfuzzer/pull/4 is merged I think

**Comment by evverx** [comment]
@mrc0mmand the PR looks good to me. If there is nothing else that can be added on top here I think it should be good to go.

**Comment by evverx** [comment]
I'll go ahead and merge it because it should make it easier to turn off the memory leak detector using a long option (instead of just replacing `return 3` with `return 0` :-)). Thanks!

**Comment by mrc0mmand** [comment]
> @mrc0mmand thanks! I'll take a closer look a bit later today but in the meantime could you run something like
> 
> ```shell
> dfuzzer --help
> dfuzzer --verbose --bus ...
> ```
> 
> on GHAction in addition to the commands with short options just to make sure the long options are more or less in good shape as well?

That was something I definitely wanted to add but it somehow slipped my mind, thanks :-)

> 
> > The tabs everywhere are driving me nuts (see the formatting of the longopts struct), but it is what it is :-)
> 
> Considering that `dfuzzer` is no longer actively maintained and the patches are unlikely to land there I think it should be possible to just reformat the code in a separate PR.

Yeah, that would make sense.


> @mrc0mmand the PR looks good to me. If there is nothing else that can be added on top here I think it should be good to go.

Yup, it should be ready to go, I just got a bit distracted after pushing the update :-)

**Pull request merged**
